test("Pass", () => {});

test("Fail", () => {
  throw new Error("Failure!");
});
